include: package:flutter_lints/flutter.yaml

targets:
  $default:
    builders:
      freezed:
        options:
          generic_argument_factories: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

